"""
One-time script to extract all prompts from prompts.py into txt files
Run this once to migrate from hardcoded prompts to file-based prompts
"""
import re
from pathlib import Path

# Read prompts.py
prompts_file = Path(__file__).parent / "prompts.py"
with open(prompts_file, 'r', encoding='utf-8') as f:
    content = f.read()

# Create templates/prompts directory
templates_dir = Path(__file__).resolve().parents[1] / 'templates' / 'prompts'
templates_dir.mkdir(parents=True, exist_ok=True)

print(f"Extracting prompts to: {templates_dir}")

# Extract CONCEPT_EXTRACTION_BY_SUBJECT
print("\n=== CONCEPT EXTRACTION PROMPTS ===")
concept_pattern = r'"([^"]+)":\s*"""(.*?)"""(?=\s*,?\s*(?:"|}))'
concept_match = re.search(r'CONCEPT_EXTRACTION_BY_SUBJECT\s*=\s*{(.*?)}(?=\s*#|\s*SCRIPT)', content, re.DOTALL)
if concept_match:
    concept_block = concept_match.group(1)
    for match in re.finditer(concept_pattern, concept_block, re.DOTALL):
        subject = match.group(1)
        prompt = match.group(2).strip()
        
        # Save to file
        filename = f"concept_extraction_{subject.replace(' ', '_')}.txt"
        file_path = templates_dir / filename
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(prompt)
        print(f"✓ {filename} ({len(prompt)} chars)")

# Extract SCRIPT_PROMPTS_BY_SUBJECT (these are generated by get_script_prompt function)
print("\n=== SCRIPT GENERATION PROMPTS ===")
print("Note: Script prompts are generated dynamically by get_script_prompt() function")
print("Extracting subject focus blocks and base template...")

# Extract subject focuses
focus_pattern = r'"([^"]+)":\s*"""(.*?)"""(?=\s*,?\s*(?:"|}))'
focus_match = re.search(r'subject_focuses\s*=\s*{(.*?)}', content, re.DOTALL)
if focus_match:
    focus_block = focus_match.group(1)
    subject_focuses = {}
    for match in re.finditer(focus_pattern, focus_block, re.DOTALL):
        subject = match.group(1)
        focus = match.group(2).strip()
        subject_focuses[subject] = focus

# Extract base script prompt template
base_template_match = re.search(r'prompt\s*=\s*f"""(.*?)"""', content, re.DOTALL)
if base_template_match:
    base_template = base_template_match.group(1).strip()
    
    # Generate script prompts for each subject
    for subject, focus in subject_focuses.items():
        # Replace {subject_focus} placeholder with actual focus
        full_prompt = base_template.replace("{subject_focus}", focus)
        
        filename = f"script_generation_{subject.replace(' ', '_')}.txt"
        file_path = templates_dir / filename
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(full_prompt)
        print(f"✓ {filename} ({len(full_prompt)} chars)")

# Extract MCQ_PROMPTS_BY_SUBJECT (generated by get_mcq_prompt function)
print("\n=== MCQ GENERATION PROMPTS ===")
mcq_focus_match = re.search(r'def get_mcq_prompt.*?subject_focuses\s*=\s*{(.*?)}', content, re.DOTALL)
if mcq_focus_match:
    mcq_focus_block = mcq_focus_match.group(1)
    mcq_subject_focuses = {}
    for match in re.finditer(focus_pattern, mcq_focus_block, re.DOTALL):
        subject = match.group(1)
        focus = match.group(2).strip()
        mcq_subject_focuses[subject] = focus

# Extract base MCQ prompt template
mcq_template_match = re.search(r'def get_mcq_prompt.*?prompt\s*=\s*f"""(.*?)""".*?return prompt', content, re.DOTALL)
if mcq_template_match:
    mcq_base_template = mcq_template_match.group(1).strip()
    
    # Generate MCQ prompts for each subject
    for subject, focus in mcq_subject_focuses.items():
        full_prompt = mcq_base_template.replace("{subject_focus}", focus)
        
        filename = f"mcq_generation_{subject.replace(' ', '_')}.txt"
        file_path = templates_dir / filename
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(full_prompt)
        print(f"✓ {filename} ({len(full_prompt)} chars)")

# Extract REGENERATION_PROMPTS
print("\n=== REGENERATION PROMPTS ===")
regen_match = re.search(r'REGENERATION_PROMPTS\s*=\s*{(.*?)}(?=\s*$)', content, re.DOTALL)
if regen_match:
    regen_block = regen_match.group(1)
    regen_prompts = {}
    
    for match in re.finditer(r'"([^"]+)":\s*"""(.*?)"""', regen_block, re.DOTALL):
        prompt_type = match.group(1)
        prompt_text = match.group(2).strip()
        regen_prompts[prompt_type] = prompt_text
    
    # Save all regeneration prompts in one file
    regen_file = templates_dir / "regeneration_prompts.txt"
    with open(regen_file, 'w', encoding='utf-8') as f:
        for prompt_type, prompt_text in regen_prompts.items():
            f.write(f"=== {prompt_type} ===\n")
            f.write(prompt_text)
            f.write("\n\n")
    print(f"✓ regeneration_prompts.txt ({len(regen_prompts)} types, {sum(len(p) for p in regen_prompts.values())} total chars)")
    for prompt_type in regen_prompts.keys():
        print(f"  - {prompt_type}")

print("\n✅ All prompts extracted successfully!")
print(f"📁 Saved to: {templates_dir}")
print("\nNext steps:")
print("1. Review generated txt files")
print("2. Update prompt_loader.py SUBJECTS list to match actual subjects")
print("3. Test: python -c 'from prompt_loader import *; print(len(CONCEPT_EXTRACTION_BY_SUBJECT))'")
print("4. If working, delete prompts.py")
